services:
  perfex:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - perfex_data:/var/www/html/
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=perfex_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  perfex_data: 
    driver: local
  mysql_data: 
    driver: local